// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC5dnjPhEu-05DZR7lB5EizY6znlGsLeXM',
//     appId: '1:166016380381:web:ddfab132be2fe2ec9b9a34',
//     messagingSenderId: '166016380381',
//     projectId: 'safecity-app-f1fde',
//     authDomain: 'safecity-app-f1fde.firebaseapp.com',
//     storageBucket: 'safecity-app-f1fde.firebasestorage.app',
//     measurementId: 'G-EPD3JDVEGK',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBQVsjrxkeWfi8izsbhO74p7PGZ9fGpJcA',
//     appId: '1:166016380381:android:86f1c6a7a3cabec99b9a34',
//     messagingSenderId: '166016380381',
//     projectId: 'safecity-app-f1fde',
//     storageBucket: 'safecity-app-f1fde.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCPKUQ0cmHLfuhqEgdicZ-hhP4ivS4FgQY',
//     appId: '1:166016380381:ios:c1e445238177226c9b9a34',
//     messagingSenderId: '166016380381',
//     projectId: 'safecity-app-f1fde',
//     storageBucket: 'safecity-app-f1fde.firebasestorage.app',
//     iosBundleId: 'com.safecity.safecity',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCPKUQ0cmHLfuhqEgdicZ-hhP4ivS4FgQY',
//     appId: '1:166016380381:ios:c1e445238177226c9b9a34',
//     messagingSenderId: '166016380381',
//     projectId: 'safecity-app-f1fde',
//     storageBucket: 'safecity-app-f1fde.firebasestorage.app',
//     iosBundleId: 'com.safecity.safecity',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC5dnjPhEu-05DZR7lB5EizY6znlGsLeXM',
//     appId: '1:166016380381:web:b013cde4d336a9b99b9a34',
//     messagingSenderId: '166016380381',
//     projectId: 'safecity-app-f1fde',
//     authDomain: 'safecity-app-f1fde.firebaseapp.com',
//     storageBucket: 'safecity-app-f1fde.firebasestorage.app',
//     measurementId: 'G-1Z962PBWCC',
//   );

// }